Proyecto-DAW/daw/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'', include('mapa.urls')),
]
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    ##urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Proyecto-DAW/mapa/urls.py
from django.conf.urls import url
from . import views

app_name = "mapa"

urlpatterns = [

    url(r'^$',views.index,name='index'),

    url(r'^acerca/$',views.acerca,name='acerca'),

    url(r'^contacto/$',views.contacto,name='contacto'),

    url(r'^desarrolladores/$',views.desarrolladores,name='desarrolladores'),

    url(r'^faq/$',views.faq,name='faq'),

    url(r'^galeria/$',views.galeria,name='galeria'),

    url(r'^programadores/$',views.programadores,name='programadores'),

    url(r'^lineaDeTiempo/$',views.timeline,name='timeline'),

]

Proyecto-DAW/mapa/models.py
from django.db import models

class facultad(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre


class coordinates(models.Model):
    facultad = models.ForeignKey(facultad,on_delete=models.CASCADE)
    latitude = models.FloatField()
    longitude = models.FloatField()
    imagenes = models.CharField(max_length=1000)

    def __str__(self):
        return "coordenadas = (" + self.latitude + ", " + self.longitude + ")"

Proyecto-DAW/mapa/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import Context, loader

# Create your views here.
def index(request):
    return render(request,"mapa/index.html")
def acerca(request):
    return render(request,"mapa/acerca.html")
def contacto(request):
    return render(request,"mapa/contacto.html")
def desarrolladores(request):
    return render(request,"mapa/Desarrolladores.html")
def faq(request):
    return render(request,"mapa/faqs.html")
def galeria(request):
    return render(request,"mapa/galeria.html")
def programadores(request):
    return render(request,"mapa/programadores.html")
def timeline(request):
    return render(request,"mapa/timeline.html")

Proyecto-DAW/mapa/templates/mapa/Desarrolladores.html
{% extends 'mapa/base.html' %}
{% load static from staticfiles %}
{% block title  %}Polifinder{% endblock %}
{% block estilo %}
			<link rel="stylesheet" href="{% static 'css/AcercaDeEstilo.css' %}" type="text/css">
			<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

			<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
			<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
{% endblock %}
{% block body %}
	<div class="container-fluid" id="contenido" >
		<div class="row">
			<div class="col-lg-1"></div>
			<div class="col-lg-10">
				<div class="jumbotron">
					<header>
						<h1>Hoja de Vida</h1>
					</header>
					<div id="nombres" class ="box">
						<div class="box-group">
							<div class="row">
								<div class="col-3"></div>
								<div class="col-6">
									<div class="head">
										<h2>Luis Cruz</h2>
										<img src="galeria/foto.jpg" id ="profile" class="foto"/>
									</div>
								</div>
								<div class="col-3"></div>
							</div>
						</div>
						<p>
							Ingenieria en Computacion<br>
							Escuela Superior Politecnica Del Litoral(ESPOL)<br>
							Guayaquil, Ecuador<br>
							593<br>
						</p>
						<br>
					</div>
					<div id="datos" class ="box">
						<h2>Datos Personales</h2>
						<p>
							Sauces 7, manzana 381, villa 8<br>
							0968388887<br>
						</p>
					</div>
					<div id="educacion" class ="box">
						<h2>Educacion</h2>
						<div class="box-group">
							<div class="row">
								<div class="col-6">
									<div class="contenido">
										<img src="espol.png" class="foto" id="uni"/>
										<h3 class="institucion">Universidad</h3>
										<p class="periodo">Año de inicio - Año de finalizacion</p>
										<p>
											PYTHON - Aprendi lo basico de programacion<br>
											JAVA - Aprendi a manejar objetos<br>
											HTML - Aprendi diseño web<br>
											C++ - Aprendi a manejar memoria<br>
										</p>
										<hr class="separador">
									</div>
								</div>
								<div class="col-6">
									<div class="contenido">
										<img src="logo.jpg" class="foto" id="cole"/>
										<h3 class="institucion">Colegio</h3>
										<p class="periodo">Año de inicio - Año de finalizacion</p>
										<p>
											Logica Matematica<br>
											Quimica Basica<br>
											Manejo de Herramientas de Office<br>
											Fisica de colegio<br>
										</p>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div id="habilidades" class ="box">
						<h2>Habilidades Tecnicas</h2>
						<div class="contenido">
							<div id="habilidad">
								<div class="habilidad">
									<div class=cantidad_h>15</div>
									<div>HTML</div>
								</div>
								<div class="habilidad">
									<div class=cantidad_h>2</div>
									<div>CSS3</div>
								</div>
								<div class="habilidad">
									<div class=cantidad_h>5</div>
									<div>PYTHON</div>
								</div>
								<div class="habilidad">
									<div class=cantidad_h>2</div>
									<div>JAVA</div>
								</div>
								<br>
							</div>
						</div>
						<br>
					</div>
				</div>
			</div>
			<div class="col-lg-1"></div>
		</div>
	</div>
{% endblock %}

Proyecto-DAW/mapa/templates/mapa/acerca.html
{% extends 'mapa/base.html' %}
{% load static from staticfiles %}
{% block title  %}Polifinder{% endblock %}
{% block estilo %}
	<link rel="stylesheet" href="{% static 'css/AcercaDeEstilo.css' %}" type="text/css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link href='http://fonts.googleapis.com/css?family=Exo' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Joti+One' rel='stylesheet' type='text/css'>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<style type="text/css">
		/* fuentes en nuestro disco duro */
		@font-face {
			font-family: "SignPainter-HouseScript";
			src: url("fuente_SignPainter-HouseScript.ttf") format("truetype");
		}
		@font-face {
			font-family: "Quicksand-Bold Regular";
			src: url("fuente_Quicksand-Bold.otf") format("opentype");
		}
		@font-face{
			font-family: "SignPainter-HouseScript-IE";
			src: url("fuente_SignPainter-HouseScript.eot");
		}
		.fuente-1{font-family:"SignPainter-HouseScript";font-size:20px;}
		.fuente-2{font-family:"Quicksand-Bold Regular";font-size: 20px;}
		.fuente-IE{font-family:"SignPainter-HouseScript-IE";font-size:20px;}
		/* fuentes de google */
		.fuente-Exo{font-family:"Exo";font-size:20px;}
		.fuente-JotiOne{font-family:"Joti One";font-size:20px;}
	</style>
{% endblock %}
{% block body %}

		<div class="row">
			<div class="col-lg-1"></div>
			<div class="col-lg-10">
				<div class="jumbotron">
					<div class="wrapper"><img src="{% static 'galeria/fondo-acerca.jpg' %}" class="img-responsive"></div>
					<h1>Misión</h1>
					<p><div class='fuente-Exo'>Ayudar a la comunidad politecnica, en especial a los novatos, ya que todos alguna vez lo fuimos</div></p>
					<p></p>
					<h1>Visión</h1>
					<p><div class='fuente-Exo'>Formar parte de las herramientas mas usadas por los politecnicos recien ingresados</div></p>
				</div>
			</div>
			<div class="col-lg-1"></div>
		</div>

{% endblock %}

Proyecto-DAW/mapa/templates/mapa/base.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
		<meta name="description" content="Foro de temas variados de ESPOL">
		<meta name = "keywords" content = "Buscar, Aulas,espol">
        <title>{% block title %}{% endblock %}</title>

        {% load staticfiles %}

		{% block estilo %}{% endblock %}

	</head>
	<body>
		<div class="container">
            <nav class="navbar navbar-inverse navbar-fixed-top" style="background-color: #1A2421;">
				<div class="container-fluid">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>

						</button>
						<a class="navbar-brand" href="{% url 'mapa:index' %}">PoliFinder</a>
					</div>
					<div class="collapse navbar-collapse" id="myNavbar">
						<ul class="nav navbar-nav">
							<li class="active"><a href="{% url 'mapa:index' %}">Inicio</a></li>
							<li class="dropdown">
								<a class="dropdown-toggle" data-toggle="dropdown">Acerca
								<span class="caret"></span></a>
								<ul class="dropdown-menu">
									<li><a href="{% url 'mapa:acerca' %}">Vision y mision</a></li>
									<li><a href="{% url 'mapa:desarrolladores' %}">Desarrolladores</a></li>
									<li><a href="{% url 'mapa:timeline' %}">Linea de Tiempo</a></li>
								</ul>
							</li>
							<li><a href="{% url 'mapa:galeria' %}">Galeria</a></li>
							<li><a href="{% url 'mapa:faq' %}">FAQ's</a></li>
							<li><a href="{% url 'mapa:contacto' %}">Contactenos</a></li>
						</ul>
					</div>
				</div>
			</nav>
            {% block body %}
            {% endblock %}

		    <footer>
				<div class="footer" id="footer">
					<div class="container">
						<div class="row">
							<div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
								<h3>Menu</h3>
								<ul>
									<li> <a href="{% url 'mapa:index' %}"> Inicio </a> </li>
									<li> <a href="{% url 'mapa:acerca' %}"> Acerca de </a> </li>
									<li> <a href="{% url 'mapa:galeria' %}"> Galeria </a> </li>
									<li> <a href="{% url 'mapa:faq' %}"> FAQ </a> </li>
									<li> <a href="{% url 'mapa:contacto' %}"> Contactenos </a> </li>
								</ul>
							</div>
							<div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">

							</div>
							<div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">

							</div>
							<div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">

							</div>
							<div class="col-lg-3  col-md-3 col-sm-6 col-xs-12 ">
								<h3> Contactenos </h3>
								<ul>
									<li>
										<div class="input-append newsletter-box text-center">
											<input type="text" class="full text-center" placeholder="Email ">
											<button class="btn  bg-gray" type="button"> lgcruz@espol.edu.ec <i class="fa fa-long-arrow-right"> </i> </button>
										</div>
									</li>
								</ul>
								<ul class="social">
									<li> <a href="https://www.facebook.com/"> <i class=" fa fa-facebook">   </i> </a> </li>
									<li> <a href="https://twitter.com/"> <i class="fa fa-twitter">   </i> </a> </li>
									<li> <a href="https://plus.google.com/"> <i class="fa fa-google-plus">   </i> </a> </li>
									<li> <a href="https://www.pinterest.es/"> <i class="fa fa-pinterest">   </i> </a> </li>
									<li> <a href="https://www.youtube.com/channel/UCBTW2oT9cV-3rJ3jOTgmTcg"> <i class="fa fa-youtube">   </i> </a> </li>
								</ul>
							</div>
						</div>
						<!--/.row-->
					</div>
					<!--/.container-->
				</div>
				<!--/.footer-->

				<div class="footer-bottom">
					<div class="container">
						<p class="pull-left"> Copyright © 2017. All right reserved. </p>
						<div class="pull-right">
							<ul class="nav nav-pills payments">
                				<li><i class="fa fa-cc-visa"></i></li>
								<li><i class="fa fa-cc-mastercard"></i></li>
								<li><i class="fa fa-cc-amex"></i></li>
								<li><i class="fa fa-cc-paypal"></i></li>
							</ul>
						</div>
					</div>
				</div>
				<!--/.footer-bottom-->
			</footer>

        </div>
	</body>
</html>

Proyecto-DAW/mapa/templates/mapa/contacto.html
{% extends 'mapa/base.html' %}
{% load static from staticfiles %}
{% block title  %}Polifinder{% endblock %}
{% block estilo %}
	<link rel="stylesheet" href="{% static 'css/AcercaDeEstilo.css' %}" type="text/css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
{% endblock %}
{% block body %}
	<div class="container-fluid" id="contenido" >
		<div class="row">
			<div class="col-lg-1"></div>
			<div class="col-lg-10">
				<div class="jumbotron">
					<table>
						<tr>
							<p>Si tienes alguna duda, escribenos</p>
							<td>
							   <table border="0" cellpadding="0" cellspacing="0" width="40%">
								   <tr>
									   <td width="70%">Nombre: </td>
									   <td width="50%"><input type="text" size="53" name="T1" placeholder="Nombre"></td>
								   </tr>
								   <tr>
									   <td width="70%">Email: </td>
									   <td width="50%"><input type="text" size="53" name="T2" placeholder="email"></td>
								   </tr>
								   <tr>
									   <td width="70%">Asunto: </td>
									   <td width="50%"><input type="text" size="53" name="T3" placeholder="Asunto"></td>
								   </tr>
								   <tr>
									   <td width="70%">Mensaje: </td>
									   <td width="50%"><textarea class="form-control" rows="5"></textarea></td>
								   </tr>
								   <tr>
									   <td width="50%"><button type="button" class="btn btn-success" >Enviar</button></td>
								   </tr>
							   </table>
							</td>
							<td>
							</td>
						</tr>
					</table>
				</div>
			</div>
			<div class="col-lg-1"></div>
		</div>
	</div>
{% endblock %}

Proyecto-DAW/mapa/templates/mapa/faqs.html
{% extends 'mapa/base.html' %}
{% load static from staticfiles %}
{% block title  %}Polifinder{% endblock %}
{% block estilo %}
			<link rel="stylesheet" href="{% static 'css/AcercaDeEstilo.css' %}" type="text/css">
			<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
			<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
			<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
{% endblock %}
{% block body %}
	<div class="container-fluid" id="contenido" >
		<div class="row">
			<div class="col-lg-1"></div>
			<div class="col-lg-10">
				<div class="jumbotron">
					<table>
						<tr>
							<h2>Preguntas Frecuentes</h2>
						</tr>
						<tr>
							<p>1.- ¿Que es la ESPOL?</p><li><a class="pregunta" href="1.html">respuesta</a></li>
						</tr>
						<tr>
							<p>2.- ¿Que es la FIEC?</p><li><a href="2.html">respuesta</a></li>
						</tr>
						<tr>
							<p>3.- ¿Que es la FCSH?</p><li><a href="3.html">respuesta</a></li>
						</tr>
						<tr>
							<p>4.- ¿Que es la FIMCP?</p><li><a href="4.html">respuesta</a></li>
						</tr>
						<tr>
							<p>5.- ¿Que es la FICT?</p><li><a href="5.html">respuesta</a></li>
						</tr>
						<tr>
							<p>6.- ¿Que es la FIMCBOR?</p><li><a href="6.html">respuesta</a></li>
						</tr>
						<tr>
							<p>7.- ¿Que es la FCV?</p><li><a href="7.html">respuesta</a></li>
						</tr>
						<tr>
							<p>8.- ¿Que es EDCOM?</p><li><a href="8.html">respuesta</a></li>
						</tr>
						<tr>
							<p>9.- ¿Que es el CELEX?</p><li><a href="9.html">respuesta</a></li>
						</tr>
						<tr>
							<p>10.- ¿Que es el parque AJA?</p><li><a href="10.html">respuesta</a></li>
						</tr>
						<tr>
							<p>11.- ¿Que es VINCULOS CON LA SOCIEDAD?</p><li><a href="11.html">respuesta</a></li>
						</tr>
					</table>
				</div>
			</div>
			<div class="col-lg-1"></div>
		</div>
	</div>
{% endblock %}

Proyecto-DAW/mapa/templates/mapa/galeria.html
{% extends 'mapa/base.html' %}
{% load static from staticfiles %}
{% block title  %}Polifinder{% endblock %}
{% block estilo %}
			<link rel="stylesheet" href="{% static 'css/estilo_galeria.css' %}" type="text/css">
			<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
			<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
			<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
{% endblock %}
{% block body %}
	<div class="container-fluid" id="contenido" >
		<div class="row">
			<div class="col-lg-1"></div>
			<div class="col-lg-10">
				<div class="jumbotron">
					<div class= "container-fluid" id="ContenedorGaleria">
						<div class="row 1">
							<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4" id ="contenedorFila1">
								<img src="{% static 'galeria/fiec.png' %}" width="280" height="260"  /><span><br/>
								FIEC</span>
							</div>
							<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4" id="contenedorFila2">
								<img src="{% static 'galeria/fict.png' %}" width="280" height="260"  /><span><br/>
								FICT</span>
							</div>
							<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4" id ="contenedorFila3">
								<span><img src="{% static 'galeria/biblioteca.jpg' %}" width="280" height="260" /><br/>
								CIB-Biblioteca</span>
							</div>
						</div>
						<div class="row 2">
							<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4" id ="contenedorFila1">
								<img src="{% static 'galeria/tecnologias.jpg' %}" width="280" height="260"  /><span><br/>
								Tecnologia</span>
							</div>
							<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4" id="contenedorFila2">
								<span><img src="{% static 'galeria/Rectorado.jpg' %}" width="280" height="260" /><br/>
								Rectorado</span>
							</div>
							<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4" id ="contenedorFila3">
								<img src="{% static 'galeria/celex.png' %}" width="280" height="260"  /><span><br/>
								CELEX</span>
							</div>
						</div>
						<div class="row 3">
							<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4" id ="contenedorFila1">
								<span><img src="{% static 'galeria/edcom.png' %}" width="280" height="260" /><br/>
								EDCOM</span>
							</div>
							<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4" id="contenedorFila2">
								<img src="{% static 'galeria/fimcbor.png' %}" width="280" height="260"  /><span><br/>
								FIMCBOR</span>
							</div>
							<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4" id ="contenedorFila3">
								<img src="{% static 'galeria/fimcp.png' %}" width="280" height="260" /><span><br/>
								FIMCP</span>
							</div>
						</div>
						<div class="row 4">
							<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4" id ="contenedorFila1">
								<img src="{% static 'galeria/gym_servidores.jpg' %}" width="280" height="260"  /><span><br/>
								Gimnasio de Servidores</span>
							</div>
							<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4" id="contenedorFila2">
								<img src="{% static 'galeria/Admisiones.png' %}" width="280" height="260" /><span><br/>
								Admisiones</span>
							</div>
							<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4" id="contenedorFila3">
								<img src="{% static 'galeria/fsch.png' %}" width="280" height="260" /><span><br/>
								FCSH</span>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-lg-1"></div>
	</div>
	
{% endblock %}
	

Proyecto-DAW/mapa/templates/mapa/index.html
{% extends 'mapa/base.html' %}
{% load static from staticfiles %}
{% block title  %}Polifinder{% endblock %}
{% block estilo %}
	<!--CSS-->
	<link rel="stylesheet" href="{% static 'css/estilo_index.css' %}" type="text/css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<!--leaflet-->
	<link rel="stylesheet" href="https://unpkg.com/leaflet@1.2.0/dist/leaflet.css"
	integrity="sha512-M2wvCLH6DSRazYeZRIm1JnYyh22purTM+FDB5CsyxtQJYeKq83arPe5wgbNmcFXGqiSH2XR8dT/fJISVA1r/zQ=="
	crossorigin=""/>
	<link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}">
	<!--JS-->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<script src="https://unpkg.com/leaflet@1.2.0/dist/leaflet.js"
	integrity="sha512-lInM/apFSqyy1o6s89K4iQUKg6ppXEgsVxT35HbzUupEVRh2Eu9Wdl4tHj7dZO0s1uvplcYGmt3498TtHq+log=="
	crossorigin=""></script>
	<script src="http://code.jquery.com/jquery-1.8.3.js"></script>
	<script src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>
	<script src="{% static 'js/jquery-ui.min.js' %}"></script>
	<style>
		.ui-autocomplete {
			max-height: 200px;
			overflow-y: auto;
			/* prevent horizontal scrollbar */
			overflow-x: hidden;
			/* add padding to account for vertical scrollbar */
			padding-right: 20px;
		}
	</style>
{% endblock %}
{% block body %}
	<div class="container-fluid" id="contenido" >
		<div class="row">
			<div class="col-lg-12">
				<div class="jumbotron">
					<div class="row">
						<div class="col-lg-3">
							<div class="container">
								<div class="ui-widget">
									<label for="tags1">Destino: </label>
									<input id="tags1" spellcheck="false">
								</div>
								<div><p></p></div>
								<!--<div class="ui-widget">
										<label for="tags2">Partida: </label>
										<input id="tags2" spellcheck="false">
									</div>-->
							</div>
						</div>
						<div class="col-lg-9">
							<div id="mapid"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	{% load staticfiles %}
	<script src="{% static 'js/leafletjs.js' %}"></script>
{% endblock %}

Proyecto-DAW/mapa/templates/mapa/programadores.html
{% extends 'mapa/base.html' %}
{% load static from staticfiles %}
{% block title  %}Polifinder{% endblock %}
{% block estilo %}
	<link rel="stylesheet" href="{% static 'css/desarrolladores.css' %}" type="text/css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
{% endblock %}
{% block body %}
	<div class="container-fluid" id="contenido" >
		<div class="row">
			<div class="col-lg-1"></div>
			<div class="col-lg-10">
				<div class="jumbotron">
					<header>
						<h1>Hoja de Vida</h1>
					</header>
					<div id="nombres" class ="box">
						<div class="box-group">
							<div class="row">
								<div class="col-3"></div>
								<div class="col-6">
									<div class="head">
										<h2>Luis Cruz</h2>
										<img src="foto.jpg" id ="profile" class="foto"/>
									</div>
								</div>
								<div class="col-3"></div>
							</div>
						</div>
						<p>
							Ingenieria en Computacion<br>
							Escuela Superior Politecnica Del Litoral(ESPOL)<br>
							Guayaquil, Ecuador<br>
							593<br>
						</p>
						<br>
					</div>
					<div id="datos" class ="box">
						<h2>Datos Personales</h2>
						<p>
							Sauces 7, manzana 381, villa 8<br>
							0968388887<br>
						</p>
					</div>
					<div id="educacion" class ="box">
						<h2>Educacion</h2>
						<div class="box-group">
							<div class="row">
								<div class="col-6">
									<div class="contenido">
										<img src="espol.png" class="foto" id="uni"/>
										<h3 class="institucion">Universidad</h3>
										<p class="periodo">Año de inicio - Año de finalizacion</p>
										<p>
											PYTHON - Aprendi lo basico de programacion<br>
											JAVA - Aprendi a manejar objetos<br>
											HTML - Aprendi diseño web<br>
											C++ - Aprendi a manejar memoria<br>
										</p>
										<hr class="separador">
									</div>
								</div>
								<div class="col-6">
									<div class="contenido">
										<img src="logo.jpg" class="foto" id="cole"/>
										<h3 class="institucion">Colegio</h3>
										<p class="periodo">Año de inicio - Año de finalizacion</p>
										<p>
											Logica Matematica<br>
											Quimica Basica<br>
											Manejo de Herramientas de Office<br>
											Fisica de colegio<br>
										</p>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div id="habilidades" class ="box">
						<h2>Habilidades Tecnicas</h2>
						<div class="contenido">
							<div id="habilidad">
								<div class="habilidad">
									<div class=cantidad_h>15</div>
									<div>HTML</div>
								</div>
								<div class="habilidad">
									<div class=cantidad_h>2</div>
									<div>CSS3</div>
								</div>
								<div class="habilidad">
									<div class=cantidad_h>5</div>
									<div>PYTHON</div>
								</div>
								<div class="habilidad">
									<div class=cantidad_h>2</div>
									<div>JAVA</div>
								</div>
								<br>
							</div>
						</div>
						<br>
					</div>
				</div>
			</div>
			<div class="col-lg-1"></div>
		</div>
	</div>
{% endblock %}